### ISSUE TITLE
Are bed files coordinates compatible with hg19 or hg38 ?

### ISSUE THREAD

**Issue by YoannPa** [rashidalabri/cancer-rre-paper-analysis#1]
Hi !
In the folder **cancer-rre-paper-analysis/tree/main/analysis/data/input/** you share several bed annotation files with cCREs and rREs coordinates.
Are these annotation compatible with hg19 or hg38 human genome assembly ?

Thank you very much in advance for the clarification.
Best regards.

**Comment by rashidalabri** [comment]
Hello @YoannPa! Unless specified otherwise in the file name or in the Jupyter notebook, the bed files are in hg19 coordinates.
